---
- hosts: catalog_host:dispatcher_host:scheduler_host:archiver_host
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    - name: "Installing misc packages"
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        update_cache: yes
    - name: "Adding Docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: "Adding Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
        filename: docker
    - name: "Installing 'docker-ce'"
      apt:
        name: "docker-ce"
        update_cache: yes
- hosts: archiver_host:dispatcher_host
  become: true
  tasks:
    - name: Installing NFS Common
      apt:
        name: ['nfs-common']
        update_cache: yes
- hosts: temp_storage_host
  become: true
  tasks:
    - name: Installing NFS Server
      apt:
        name: ['nfs-kernel-server']
        update_cache: yes